version: '3'
services:
  web: 
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  mongo:
    image:  mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daposta
      - MONGO_INITDB_ROOT_PASSWORD=passw
    volumes:
      - mongo-db:/data/db



volumes:
  mongo-db: